### ISSUE TITLE
多进程和文件处理之间的问题

### ISSUE THREAD

**Issue by CrazyTianC** [williezh/linuxtools#1]
在多进程中，使用codecs打开文件，就会出现部分进程不执行的情况。(并且改成while '\n' not in f.read(1))

有点不太明白是怎么回事，求教

**Comment by waketzheng** [comment]
应该是codecs的问题，可以改为用终端执行，或是将python2换为python3试试。

另：该账户基本已不再使用，最新版本请移步：[https://github.com/waketzheng/wordcounter](https://github.com/waketzheng/wordcounter)
